events {}

http {
    upstream filebrowser {
        server filebrowser:80; # Servizio FileBrowser
    }

    server {
        listen 80;

        # Inoltra tutte le richieste a FileBrowser
        location / {
            proxy_pass http://filebrowser;
            proxy_set_header X-User-Header "admin"; # Header per l'AuthN - proxy header mode
        }
    }
}