events {}

http {
    upstream pep {
        server pep:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass         http://pep;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            # In futuro questo header verrà popolato da Keycloak
            proxy_set_header   X-User-Header     "admin";
        }
    }
}